## Naming convetion
# - target: <golden_signal>-<target_type>-<metric>
# Where:
#   - <golden_signal> is one of:
#     - lat - Latency
#     - err - Errors
#     - sat - Saturation
#     - trf - Traffic
- name: lat_eks_service_requests
  comparison_operator: GreaterThanOrEqualToThreshold
  evaluation_periods: 1
  metric_name: Latency
  namespace: ApplicationSignals
  statistic: p99
  period: 60
  default_threshold: 100
  datapoints_to_alarm: 1
  dimensions:
    Environment: "eks:${eks.cluster_name}/${eks.namespace}"
    Service: "${service_name}"
  description: |
    Latency threshold for EKS service requests has been breached.
    * Percentile: __p99__
    * Service: __${service_name}__
    * Namespace: __${eks.namespace}__
    * Cluster: __${eks.cluster_name}__
    * Threshold: __${try(threshold, 100)}__ ms
- name: err_eks_service_requests
  comparison_operator: GreaterThanOrEqualToThreshold
  evaluation_periods: 1
  default_threshold: 100
  datapoints_to_alarm: 1
  metric_query:
    error_rate_e1:
      expression: "errors_s1 * 100 / volume_s1"
      return_data: true
      period: 60
    errors_s1:
      metric:
        metic_name: Error
        namespace: ApplicationSignals
        statistic: Sum
        period: 60
        dimensions:
          Environment: "eks:${eks.cluster_name}/${eks.namespace}"
          Service: "${service_name}"
    volume_s1:
      metric:
        metric_name: Latency
        namespace: ApplicationSignals
        statistic: SampleCount
        period: 60
        dimensions:
          Environment: "eks:${eks.cluster_name}/${eks.namespace}"
          Service: "${service_name}"
  description: |
    Error rate for EKS service requests has been breached.
    * Service: __${service_name}__
    * Namespace: __${eks.namespace}__
    * Cluster: __${eks.cluster_name}__
    * Threshold: __${try(threshold, 100)}__ errors per period configured
- name: err_eks_service_faults
- name: sat_eks_container_cpu_utilization
- name: sat_eks_container_memory_utilization
- name: trf_eks_service_requests
  comparison_operator: GreaterThanOrEqualToThreshold
  evaluation_periods: 1
  metric_name: Latency
  namespace: ApplicationSignals
  statistic: SampleCount
  period: 60
  default_threshold: 1000
  datapoints_to_alarm: 1
  dimensions:
    Environment: "eks:${eks.cluster_name}/${eks.namespace}"
    Service: "${service_name}"
  description: |
    Requests threshold for EKS service requests has been breached.
    * Service: __${service_name}__
    * Namespace: __${eks.namespace}__
    * Cluster: __${eks.cluster_name}__
    * Threshold: __${try(threshold, 1000)}__ requests per period configured
- name: trf_eks_service_requests_per_second
- name: lat_lambda_service_requests
- name: err_lambda_service_errors
- name: sat_lambda_throttled_requests
- name: trf_lambda_service_requests